// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Flow for improving Bangla captions based on user edits.
 *
 * This file defines a Genkit flow that takes an image URL and a user-edited Bangla caption as input,
 * and uses an AI model to further improve the caption.
 *
 * @Exported Functions:
 *   - improveBanglaCaption: The main function to trigger the caption improvement flow.
 *
 * @Exported Types:
 *   - ImproveBanglaCaptionInput: Input type for the improveBanglaCaption function.
 *   - ImproveBanglaCaptionOutput: Output type for the improveBanglaCaption function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

/**
 * Input schema for the improveBanglaCaption flow.
 */
const ImproveBanglaCaptionInputSchema = z.object({
  photoUrl: z.string().describe('The URL of the image to caption.'),
  editedCaption: z.string().describe('The user-edited Bangla caption.'),
});
export type ImproveBanglaCaptionInput = z.infer<
  typeof ImproveBanglaCaptionInputSchema
>;

/**
 * Output schema for the improveBanglaCaption flow.
 */
const ImproveBanglaCaptionOutputSchema = z.object({
  improvedCaption: z.string().describe('The improved Bangla caption.'),
});
export type ImproveBanglaCaptionOutput = z.infer<
  typeof ImproveBanglaCaptionOutputSchema
>;

/**
 * Improves a Bangla caption based on user edits using an AI model.
 * @param input - The input containing the image URL and edited caption.
 * @returns The improved Bangla caption.
 */
export async function improveBanglaCaption(
  input: ImproveBanglaCaptionInput
): Promise<ImproveBanglaCaptionOutput> {
  return improveBanglaCaptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'improveBanglaCaptionPrompt',
  input: {
    schema: z.object({
      photoUrl: z.string().describe('The URL of the image to caption.'),
      editedCaption: z.string().describe('The user-edited Bangla caption.'),
    }),
  },
  output: {
    schema: z.object({
      improvedCaption: z.string().describe('The improved Bangla caption.'),
    }),
  },
  prompt: `You are an AI model specializing in generating Bangla captions for images. A user has provided an image and an initial caption.

  Please improve the given Bangla caption to be more descriptive, engaging, and relevant to the image. Consider the context and details visible in the image.

  Image URL: {{photoUrl}}
  Edited Caption: {{{editedCaption}}}

  Improved Caption:`, // Ensure that the output is only the improved caption.
});

/**
 * Genkit flow for improving Bangla captions.
 */
const improveBanglaCaptionFlow = ai.defineFlow<
  typeof ImproveBanglaCaptionInputSchema,
  typeof ImproveBanglaCaptionOutputSchema
>({
  name: 'improveBanglaCaptionFlow',
  inputSchema: ImproveBanglaCaptionInputSchema,
  outputSchema: ImproveBanglaCaptionOutputSchema,
},
async input => {
  const {output} = await prompt(input);
  return output!;
});
